### ISSUE TITLE
Why not clamp in generalized_steps?

### ISSUE THREAD

**Issue by GloryyrolG** [ermongroup/ddim#2]
Hi,

Thanks for your great work. May I ask, why you do not clamp in generalized_steps as in ddpm_steps?

https://github.com/ermongroup/ddim/blob/34d640e5180cc5ab378f84af6ed596cb0c810e6c/functions/denoising.py#L24

**Comment by AwayGithub** [comment]
@GloryyrolG @jiamings 
Hi! Recently, while working on image-to-image translation using Palette, I encountered the same question. [Here](https://github.com/lucidrains/denoising-diffusion-pytorch/issues/47#issuecomment-2768297917) are some of my observations that may help clarify this issue.

In summary:

- For DDPM, clamping is necessary at high sampling steps (around 1000) to ensure stability.
- As the step count decreases, clamping can be removed—though the exact reason remains unclear—but performance gradually degrades with fewer steps.
- Since DDIM operates at significantly fewer steps than DDPM, clamping can safely be omitted.
